# Generated by Django 5.2 on 2025-05-27 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
        ('users', '0003_child_fifty_fifty_available_child_hints_available_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.child')),
                ('powerup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.powerup')),
            ],
            options={
                'unique_together': {('child', 'powerup')},
            },
        ),
    ]
