# Generated by Django 5.2 on 2025-05-27 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_remove_user_email_parent_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('child', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='achievement', serialize=False, to='users.child')),
                ('gold', models.IntegerField(default=0)),
                ('silver', models.IntegerField(default=0)),
                ('bronze', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Achievement',
                'verbose_name_plural': 'Achievements',
            },
        ),
    ]
