# Generated by Django 5.2 on 2025-05-27 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_email_parent_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='fifty_fifty_available',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='child',
            name='hints_available',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='child',
            name='points',
            field=models.PositiveIntegerField(default=90),
        ),
    ]
