# Generated by Django 5.2.1 on 2025-05-28 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_child_fifty_fifty_available_child_hints_available_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='current_level',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='child',
            name='last_attempt_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
